apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: code-indexer
  labels:
    app: code-indexer
spec:
  selector:
    matchLabels:
      app: code-indexer
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
